"""Tests against a captured real Google results page.

The fixture is generated by ``tests/_capture_fixture.py``. If it's not present
(fresh checkout, fixture deleted), these tests skip — they are guards against
silent breakage when Google ships a DOM change, not a CI gate.
"""

from pathlib import Path

import pytest

from plsearch.parse_page import parse_page

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "google_results.html"


@pytest.fixture
def real_google_html() -> str:
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Fixture not found at {FIXTURE_PATH}. "
            "Regenerate with `uv run python tests/_capture_fixture.py`."
        )
    return FIXTURE_PATH.read_text(encoding="utf-8")


def test_parses_at_least_five_results(real_google_html: str) -> None:
    results = parse_page(real_google_html)
    assert len(results) >= 5, f"Expected ≥5 results from real Google page, got {len(results)}"


def test_every_result_has_nonempty_title(real_google_html: str) -> None:
    for result in parse_page(real_google_html):
        assert result["title"].strip(), f"Empty title in result: {result!r}"


def test_every_result_has_plausible_url(real_google_html: str) -> None:
    for result in parse_page(real_google_html):
        url = result["url"]
        assert url.startswith(("http://", "https://", "/url?")), (
            f"Unexpected URL form: {url!r}"
        )


def test_every_result_has_correct_type_field(real_google_html: str) -> None:
    for result in parse_page(real_google_html):
        assert result["type"] == "web_search_result"


def test_every_result_has_all_expected_keys(real_google_html: str) -> None:
    expected = {"type", "title", "url", "page_content", "page_age"}
    for result in parse_page(real_google_html):
        assert set(result.keys()) == expected, f"Unexpected keys in {result!r}"
